# Generated by Django 2.1.2 on 2018-11-20 09:32

import UploadDownload.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingleFileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=100)),
                ('file', models.FileField(default=None, max_length=1000, upload_to=UploadDownload.models.SingleFileUpload.loc_func)),
                ('md5sum', models.CharField(max_length=200)),
                ('file_url', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='singlefileupload',
            unique_together={('username', 'md5sum', 'file_path')},
        ),
    ]
