# Generated by Django 2.1.2 on 2018-10-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadDownload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlefileupload',
            name='file_path',
            field=models.CharField(default='', max_length=100),
        ),
    ]
