# Generated by Django 2.1.2 on 2018-11-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadDownload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlefileupload',
            name='name',
            field=models.CharField(default='s', max_length=200),
            preserve_default=False,
        ),
    ]
