# Generated by Django 2.1.2 on 2018-10-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadDownload', '0002_auto_20181024_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlefileupload',
            name='file_path',
            field=models.CharField(max_length=100),
        ),
    ]
