# Generated by Django 2.1.2 on 2018-11-23 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UploadDownload', '0002_singlefileupload_md5sum_o'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlefileupload',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authentication.SpcUser'),
        ),
    ]
