# Generated by Django 2.1.2 on 2018-11-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadDownload', '0002_singlefileupload_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='singlefileupload',
            unique_together={('username', 'name', 'file_path')},
        ),
    ]
