# Generated by Django 2.1.2 on 2018-11-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UploadDownload', '0003_auto_20181121_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlefileupload',
            name='file_path',
            field=models.CharField(max_length=1000),
        ),
    ]
