# Generated by Django 2.1.2 on 2018-11-20 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadDownload', '0003_auto_20181029_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlefileupload',
            name='name',
        ),
        migrations.AlterUniqueTogether(
            name='singlefileupload',
            unique_together={('username', 'md5sum', 'file_path')},
        ),
    ]
