# Generated by Django 2.1.2 on 2018-10-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spcuser',
            name='encryptionKey',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='spcuser',
            name='encryptionType',
            field=models.CharField(default='', max_length=100),
        ),
    ]
