# Generated by Django 2.1.2 on 2018-11-23 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spcuser',
            name='encryptionKey',
        ),
        migrations.RemoveField(
            model_name='spcuser',
            name='encryptionType',
        ),
    ]
