# Generated by Django 2.1.2 on 2018-11-21 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_spcuser_synclock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spcuser',
            name='syncLock',
        ),
    ]
