# Generated by Django 2.1.2 on 2018-10-19 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlefileupload',
            name='title',
        ),
        migrations.AddField(
            model_name='singlefileupload',
            name='file_path',
            field=models.FilePathField(default='home'),
            preserve_default=False,
        ),
    ]
