# Generated by Django 2.1.2 on 2018-10-19 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20181019_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlefileupload',
            name='file_path',
            field=models.TextField(),
        ),
    ]
