# Generated by Django 2.1.2 on 2018-10-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20181019_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlefileupload',
            name='user',
            field=models.CharField(default='anon', max_length=100),
            preserve_default=False,
        ),
    ]
