# Generated by Django 2.1.2 on 2018-10-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_singlefileupload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singlefileupload',
            name='file_path',
            field=models.CharField(max_length=100),
        ),
    ]
