# Generated by Django 2.1.2 on 2018-10-20 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_auto_20181019_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlefileupload',
            name='file_name',
        ),
    ]
